/* eslint-disable @next/next/no-img-element */
import type { Metadata } from "next";
import {getSiteContent,localized,safeUrl,type Language,type TextBlock} from "@/lib/sanity";
import {routes,labels,type PageKey} from "@/lib/routes";
import {SiteHeader,SiteFooter} from "./site-shell";
import {Catalogue} from "./catalogue";
import ContactForm from "./contact-form";
const pageDescriptions:Record<Language,Record<PageKey,string>>={sq:{home:"LindiMaps — Spatial Intelligence.",services:"Shërbime GIS, Remote Sensing, WebGIS dhe zgjidhje gjeohapësinore nga LindiMaps.",projects:"Projekte LindiMaps në WebGIS, analiza gjeohapësinore, monitorim dhe dokumentim 3D.",publications:"Publikime, kërkim shkencor, raporte dhe kontribute profesionale të LindiMaps.",activities:"Aktivitete profesionale dhe shkencore, terren, konferenca dhe trajnime nga LindiMaps.",gallery:"Arkivi vizual i LindiMaps: territor, punë në terren dhe projekte gjeohapësinore.",about:"Rreth LindiMaps, eksperienca, profili profesional, vlerat dhe bashkëpunimet.",contact:"Kontakto LindiMaps për GIS, Remote Sensing, WebGIS dhe projekte gjeohapësinore."},en:{home:"LindiMaps — Spatial Intelligence.",services:"GIS, Remote Sensing, WebGIS and geospatial services by LindiMaps.",projects:"LindiMaps projects in WebGIS, geospatial analysis, monitoring and 3D documentation.",publications:"LindiMaps publications, scientific research, reports and professional contributions.",activities:"LindiMaps professional and scientific activities, fieldwork, conferences and training.",gallery:"The LindiMaps visual archive: territory, fieldwork and geospatial projects.",about:"About LindiMaps, professional experience, values and collaborations.",contact:"Contact LindiMaps for GIS, Remote Sensing, WebGIS and geospatial projects."}};
export async function contentMetadata(lang:Language,page:PageKey):Promise<Metadata>{const {settings}=await getSiteContent();const image=safeUrl(settings?.ogImage);return {title:labels[lang][page],alternates:{canonical:routes[page][lang],languages:{"sq-AL":routes[page].sq,"en":routes[page].en,"x-default":routes[page].sq}},description:pageDescriptions[lang][page],openGraph:{title:`${labels[lang][page]} | LindiMaps`,description:pageDescriptions[lang][page],url:routes[page][lang],locale:lang==="sq"?"sq_AL":"en_US",type:"website",images:image?[{url:image,alt:"LindiMaps — Spatial Intelligence"}]:undefined},twitter:{card:"summary_large_image",title:`${labels[lang][page]} | LindiMaps`,description:pageDescriptions[lang][page],images:image?[image]:undefined},robots:{index:true,follow:true}}}
function Biography({blocks}:{blocks?:TextBlock[]}){return <div className="prose">{blocks?.filter(b=>b._type==="block").map(b=><p key={b._key}>{b.children?.map(s=>s.text).join("")}</p>)}</div>}
export default async function ContentPage({lang,page,projectCategory}:{lang:Language;page:Exclude<PageKey,"home">;projectCategory?:string}){
 const data=await getSiteContent();const {profile,settings,about}=data;const sq=lang==="sq";
 const projectFilters=[["gis","GIS"],["webgis","WebGIS"],["remote-sensing","Remote Sensing"],["3d","3D"]] as const;
 const activeProjectCategory=projectFilters.some(([value])=>value===projectCategory)?projectCategory:undefined;
 const visibleProjects=activeProjectCategory?data.projects.filter(item=>item.category===activeProjectCategory):data.projects;
 return <><SiteHeader lang={lang} page={page} settings={settings}/><main id="main" tabIndex={-1}>
  <section className="page-heading container"><p className="eyebrow">LindiMaps / {labels[lang][page]}</p><h1>{labels[lang][page]}</h1></section>
  {page==="services"&&<section className="container content-section services-editorial"><div className="section-signature"><span>01</span><i></i><small>GIS CAPABILITIES</small></div><div className="editorial-intro"><p className="eyebrow">{sq?"GIS · Remote Sensing · WebGIS":"GIS · Remote Sensing · WebGIS"}</p><h2>{sq?"Zgjidhje gjeohapësinore nga analiza te aplikacioni.":"Geospatial solutions from analysis to application."}</h2></div><Catalogue items={data.services} lang={lang} kind="services"/></section>}
  {page==="projects"&&<section className="container content-section projects-portfolio"><div className="projects-signature" aria-hidden="true"><span>02</span><i></i><small>SPATIAL WORK</small></div><div className="portfolio-intro"><p className="eyebrow">{sq?"Portofol i përzgjedhur":"Selected portfolio"}</p><div><h2>{sq?"Projekte që lidhin territorin, të dhënat dhe vendimmarrjen.":"Projects connecting territory, data and decision-making."}</h2><p>{sq?"Nga WebGIS dhe monitorimi gjeohapësinor te dokumentimi 3D, projektet paraqesin zbatime konkrete të GIS në kërkim dhe praktikë.":"From WebGIS and geospatial monitoring to 3D documentation, these projects present practical GIS applications in research and professional work."}</p></div></div><nav className="project-filters" aria-label={sq?"Filtro projektet sipas kategorisë":"Filter projects by category"}><a className={!activeProjectCategory?"active":""} href={routes.projects[lang]}>{sq?"Të gjitha":"All"}</a>{projectFilters.map(([value,label])=><a key={value} className={activeProjectCategory===value?"active":""} href={`${routes.projects[lang]}?category=${value}`}>{label}</a>)}</nav><Catalogue items={visibleProjects} lang={lang} kind="projects"/></section>}
  {page==="publications"&&<section className="container content-section publications-section"><div className="section-signature"><span>03</span><i></i><small>RESEARCH ARCHIVE</small></div>
   <div className="publications-intro"><div><p className="eyebrow">{sq?"Kërkim · Konferenca · Raporte":"Research · Conferences · Reports"}</p><h2>{sq?"Punë shkencore dhe kontribute profesionale":"Scientific work and professional contributions"}</h2></div><p>{sq?"Një arkiv i përzgjedhur i publikimeve, kapitujve, raporteve dhe materialeve të prezantuara në veprimtarinë profesionale e kërkimore të LindiMaps.":"A curated archive of publications, chapters, reports and materials presented through LindiMaps professional and research activity."}</p></div>
   <div className="publication-list">{data.publications.map((pub,index)=><article className={`publication-card ${pub.featured?"featured":""}`} key={pub._id}>
    <div className="pub-visual">{safeUrl(pub.image)?<img src={safeUrl(pub.image)} alt={lang==="en"&&pub.titleEn?pub.titleEn:pub.title} width="220" height="280" loading="lazy" decoding="async"/>:<div className="pub-placeholder" aria-hidden="true"><span>{String(index+1).padStart(2,"0")}</span><strong>LINDI<span>MAPS</span></strong><small>{pub.publicationType||"Publication"}</small></div>}</div>
    <div className="pub-content"><div className="pub-meta"><span>{pub.publicationType||"Publication"}</span>{pub.year?<span>{pub.year}</span>:null}{pub.featured?<span>{sq?"I veçuar":"Featured"}</span>:null}</div><h2>{lang==="en"&&pub.titleEn?pub.titleEn:pub.title}</h2>
    {pub.authors?.length?<p className="pub-authors">{pub.authors.join(" · ")}</p>:null}
    {pub.publisher?<p className="pub-publisher">{pub.publisher}</p>:null}
    {(sq?pub.abstractSq:pub.abstractEn)&&<p className="pub-abstract">{sq?pub.abstractSq:pub.abstractEn}</p>}
    {(lang==="en"?pub.citationEn:pub.citation)?<p className="pub-citation">{lang==="en"?pub.citationEn:pub.citation}</p>:null}
    {pub.keywords?.length?<ul className="project-tech pub-keywords" aria-label={sq?"Fjalë kyçe":"Keywords"}>{pub.keywords.map(keyword=><li key={keyword}>{keyword}</li>)}</ul>:null}
    <div className="pub-actions">{safeUrl(pub.url)&&<a className="pub-link" href={safeUrl(pub.url)} target="_blank" rel="noopener noreferrer"><span>{sq?"Publikimi online":"Online publication"}</span></a>}{safeUrl(pub.pdfUrl)&&<a className="pub-link" href={safeUrl(pub.pdfUrl)} target="_blank" rel="noopener noreferrer"><span>{sq?"Hap PDF":"Open PDF"}</span></a>}</div></div>
  </article>)}{!data.publications.length&&<div className="publication-empty"><span>01</span><h3>{sq?"Arkivi i publikimeve po përgatitet.":"The publications archive is being prepared."}</h3><p>{sq?"Publikimet do të shfaqen automatikisht këtu sapo të publikohen në CMS.":"Publications will appear here automatically once published in the CMS."}</p></div>}</div></section>}
  {page==="activities"&&<section className="container content-section activities-section"><div className="section-signature"><span>04</span><i></i><small>FIELD NOTES</small></div><div className="editorial-intro"><p className="eyebrow">{sq?"Terren · Konferenca · Trajnime":"Fieldwork · Conferences · Training"}</p><h2>{sq?"Aktivitet profesional dhe shkencor":"Professional and scientific activity"}</h2></div><div className="activity-list">{data.activities.map((item,index)=><article className="activity-item" key={item._id}>{safeUrl(item.image)&&<img src={safeUrl(item.image)} alt={localized(item,"title",lang)} loading="lazy" decoding="async"/>}<div className="activity-date"><span>{item.date?new Date(item.date+"T00:00:00").getFullYear():String(index+1).padStart(2,"0")}</span><small>{item.kind}</small></div><div><h3>{localized(item,"title",lang)}</h3><p className="activity-location">{sq?item.location:(item.locationEn||item.location)}</p><p>{localized(item,"description",lang)}</p>{safeUrl(item.url)&&<a className="text-link" href={safeUrl(item.url)} target="_blank" rel="noopener noreferrer">{sq?"Më shumë":"Learn more"} →</a>}</div></article>)}{!data.activities.length&&<p className="empty">{sq?"Aktivitetet do të shfaqen sapo të publikohen në CMS.":"Activities will appear once published in the CMS."}</p>}</div></section>}
  {page==="gallery"&&<section className="container content-section gallery-section"><div className="section-signature"><span>05</span><i></i><small>VISUAL ARCHIVE</small></div><div className="editorial-intro"><p className="eyebrow">{sq?"Arkivi vizual":"Visual archive"}</p><h2>{sq?"Territori, puna në terren dhe projektet në imazhe":"Territory, fieldwork and projects in images"}</h2></div><div className="gallery-masonry">{data.gallery.map(item=><figure className="gallery-tile" key={item._id}>{safeUrl(item.image)&&<img src={safeUrl(item.image)} alt={localized(item,"title",lang)} loading="lazy" decoding="async"/>}<figcaption><strong>{localized(item,"title",lang)}</strong><span>{localized(item,"caption",lang)}</span>{item.tags?.length?<small className="gallery-tags">{item.tags.join(" · ")}</small>:null}</figcaption></figure>)}{!data.gallery.length&&<p className="empty">{sq?"Galeria do të shfaqet sapo të publikohen imazhet në CMS.":"The gallery will appear once images are published in the CMS."}</p>}</div></section>}
  {page==="about"&&<><section className="container content-section about-profile"><div className="section-signature"><span>06</span><i></i><small>ABOUT LINDIMAPS</small></div><div className="profile-grid">{safeUrl(profile?.image)?<img className="profile-photo" src={safeUrl(profile?.image)} alt={profile?.name||"LindiMaps"} width="600" height="700" loading="lazy" decoding="async"/>:<div className="profile-monogram" aria-hidden="true">{(profile?.name||"LindiMaps").split(" ").map(n=>n[0]).join("")}</div>}<div className="profile-copy"><p className="eyebrow">{sq?"PROFIL KRYESOR · LINDIMAPS":"LEAD PROFILE · LINDIMAPS"}</p><p className="profile-name">{profile?.name}</p><h2>{localized(profile,"headline",lang)}</h2><Biography blocks={sq?profile?.bioSq:profile?.bioEn}/>{profile?.skills?.length?<ul className="project-tech profile-skills" aria-label={sq?"Aftësitë dhe teknologjitë":"Skills and technologies"}>{profile.skills.map(skill=><li key={skill}>{skill}</li>)}</ul>:null}<div className="socials profile-socials">{([["LinkedIn",profile?.linkedin],["ResearchGate",profile?.researchGate],["Google Scholar",profile?.scholar],["ORCID",profile?.orcid],["GitHub",profile?.github],["CV",profile?.cvUrl]] as const).map(([label,url])=>safeUrl(url)?<a key={label} href={safeUrl(url)} target="_blank" rel="noopener noreferrer">{label}</a>:null)}</div>{profile?.email?<p className="profile-email"><a href={`mailto:${profile.email.trim()}`}>{profile.email.trim()}</a></p>:null}</div></div></section>
  {data.team.length>0&&<section className="about-team-section"><div className="container"><div className="team-heading"><p className="eyebrow">{sq?"EKIPI":"TEAM"}</p><h2>{sq?"Njerëzit pas LindiMaps":"People behind LindiMaps"}</h2></div><div className="team-grid">{data.team.map(member=><article className={`team-card ${member.featured?"team-card-featured":""}`} key={member._id}><div className="team-photo-wrap">{safeUrl(member.image)?<img src={safeUrl(member.image)} alt={member.name} loading="lazy" decoding="async"/>:<span aria-hidden="true">{member.name.split(" ").map(n=>n[0]).join("")}</span>}</div><div className="team-card-body"><small>{sq?member.roleSq:member.roleEn||member.roleSq}</small><h3>{member.name}</h3>{(sq?member.bioSq:member.bioEn||member.bioSq)?<p>{sq?member.bioSq:member.bioEn||member.bioSq}</p>:null}<div>{safeUrl(member.linkedin)?<a href={safeUrl(member.linkedin)} target="_blank" rel="noopener noreferrer">LinkedIn</a>:null}{member.email?<a href={`mailto:${member.email.trim()}`}>Email</a>:null}</div></div></article>)}</div></div></section>}
  {(["history","values"] as const).map(section=>about?.[section]?.length?<section className={`section ${section==="values"?"soft":""}`} key={section}><div className="container"><h2>{section==="history"?(sq?"Historia jonë":"Our history"):(sq?"Vlerat tona":"Our values")}</h2><div className="grid">{about[section].map(item=><article className="card" key={item._key}><h3>{localized(item,"title",lang)}</h3><p>{localized(item,"description",lang)}</p></article>)}</div></div></section>:null)}</>}
  {page==="about"&&data.partners.length>0&&<section className="section partners-section"><div className="container"><p className="eyebrow">{sq?"Bashkëpunime":"Collaborations"}</p><h2>{sq?"Partnerë dhe institucione":"Partners and institutions"}</h2><div className="partner-grid">{[...data.partners,...data.partners].map((item,index)=><a className="partner-card" key={`${item._id}-${index}`} href={safeUrl(item.url)||undefined} target={safeUrl(item.url)?"_blank":undefined} rel={safeUrl(item.url)?"noopener noreferrer":undefined} aria-disabled={!safeUrl(item.url)||undefined}>{safeUrl(item.logo)?<img src={safeUrl(item.logo)} alt={`${item.name} logo`} loading="lazy" decoding="async"/>:<span className="partner-monogram">{item.name.slice(0,2).toUpperCase()}</span>}<strong>{item.name}</strong><small>{sq?item.roleSq:item.roleEn}</small></a>)}</div></div></section>}
  {page==="contact"&&<section className="container content-section contact-page-new"><div className="section-signature"><span>07</span><i></i><small>START A PROJECT</small></div><div className="contact-intro-new"><div><p className="eyebrow">LINDIMAPS / CONTACT</p><h2>{sq?"Le ta kthejmë idenë tënde në hartë.":"Let’s put your idea on the map."}</h2><p>{sq?"Na trego shkurt çfarë po ndërton ose analizon. Mesazhi dërgohet direkt në emailin e LindiMaps.":"Tell us briefly what you are building or analyzing. Your message is delivered directly to the LindiMaps inbox."}</p></div><div className="contact-direct"><small>{sq?"EMAIL DIREKT":"DIRECT EMAIL"}</small><a href={`mailto:${settings?.email||"contact.lindimaps@gmail.com"}`}>{settings?.email||"contact.lindimaps@gmail.com"}</a><span>{localized(settings,"location",lang)||(sq?"Tiranë, Shqipëri":"Tirana, Albania")}</span></div></div><ContactForm lang={lang}/></section>}
 </main><SiteFooter lang={lang} settings={settings}/></>
}
