import {SiteHeader,SiteFooter} from "./site-shell";
import {Catalogue} from "./catalogue";
import {routes} from "@/lib/routes";
/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import type {Metadata} from "next";
import {getSiteContent,localized,safeUrl,type Language} from "@/lib/sanity";
const copy={
sq:{title:"E ardhmja përmes GIS",text:"Konsulencë dhe zgjidhje profesionale për hartat dhe analizat tuaja hapësinore.",services:"Shërbime",projects:"Projekte",explore:"Eksploro shërbimet",contactCta:"Na kontaktoni",intro:"Analizë dhe vizualizim i avancuar i territorit",introText:"Përdorim teknologjinë më të fundit për të vizualizuar dhe analizuar çdo pikë të territorit.",allServices:"Shiko të gjitha shërbimet",allProjects:"Shiko të gjitha projektet",contactTitle:"Le ta kthejmë idenë tënde në hartë.",contactText:"Nga ideja te harta, analiza dhe aplikacioni — ndërtojmë zgjidhje gjeohapësinore të qarta dhe të përdorshme."},
en:{title:"The future through GIS",text:"Professional consulting and solutions for your maps and spatial analysis.",services:"Services",projects:"Projects",explore:"Explore services",contactCta:"Contact us",intro:"Advanced territorial analysis and visualization",introText:"We use the latest technology to visualize and analyze every point of the territory.",allServices:"View all services",allProjects:"View all projects",contactTitle:"Let’s put your idea on the map.",contactText:"From idea to map, analysis and application — we build clear, usable geospatial solutions."}
};
export async function homeMetadata(lang:Language):Promise<Metadata>{const {settings}=await getSiteContent();return{title:settings?.seoTitle||`LindiMaps | ${lang==="sq"?"Inteligjenca Hapësinore":"Spatial Intelligence"}`,description:localized(settings,"seoDescription",lang,copy[lang].text),alternates:{canonical:lang==="sq"?"/":"/en",languages:{sq:"/",en:"/en","x-default":"/"}}}}
export default async function Home({lang}:{lang:Language}){
const {home,settings,projects,services}=await getSiteContent();const t=copy[lang];const email=settings?.email?.trim()||"contact.lindimaps@gmail.com";const heroImage=safeUrl(home?.image)||"https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1920&q=80";
return <><SiteHeader lang={lang} page="home" settings={settings}/><main id="main">
<section className="hero home-map-hero" style={{"--hero-image":`url("${heroImage}")`} as React.CSSProperties}><div className="map-hero-shade" aria-hidden="true"></div><div className="map-hero-grid" aria-hidden="true"></div><div className="map-hero-contours" aria-hidden="true"></div><div className="container map-hero-center"><div className="map-hero-brand"><span className="map-hero-mark" aria-hidden="true"><svg viewBox="0 0 44 44" fill="none"><path d="M22 4L8 38l14-6 14 6L22 4Z" stroke="currentColor" strokeWidth="1.5"/><circle cx="22" cy="21" r="3.5" fill="#67dbe6"/></svg></span><strong><span className="hero-word-lindi">LINDI</span><span className="hero-word-maps">M<span className="hero-a" aria-label="A"></span>PS</span></strong></div><span className="map-hero-rule"></span><h1>BEYOND MAPS.</h1><p className="map-hero-tagline">SPATIAL INTELLIGENCE.</p><p className="map-hero-copy">{localized(home,"heroText",lang,t.text)}</p><div className="map-hero-actions"><Link href={routes.services[lang]}>{localized(home,"primaryCta",lang,t.explore)}<Arrow/></Link><Link href={routes.contact[lang]}>{localized(home,"secondaryCta",lang,t.contactCta)}<Arrow/></Link></div></div><div className="map-coordinate coord-a" aria-hidden="true">41.3275° N</div><div className="map-coordinate coord-b" aria-hidden="true">19.8187° E</div><a className="map-scroll-cue" href="#services" aria-label={lang==="sq"?"Vazhdo poshtë":"Scroll down"}><span></span></a></section>
<section className="intro modern-intro"><div className="container intro-layout"><div><p className="eyebrow">LINDIMAPS / SPATIAL INTELLIGENCE</p><h2>{localized(home,"introTitle",lang,t.intro)}</h2></div><div><p>{localized(home,"intro",lang,t.introText)}</p><div className="capability-row"><span>GIS</span><span>WebGIS</span><span>Remote Sensing</span><span>3D</span></div></div></div></section>
<section className="section services-showcase" id="services"><div className="container"><div className="section-head"><div><p className="eyebrow">01 / {t.services}</p><h2>{t.services}</h2></div><Link className="section-link" href={routes.services[lang]}>{t.allServices}<Arrow/></Link></div><Catalogue items={services.slice(0,6)} lang={lang} kind="services"/></div></section>
<section className="section projects-showcase" id="projects"><div className="container"><div className="section-head"><div><p className="eyebrow">02 / {t.projects}</p><h2>{t.projects}</h2></div><Link className="section-link" href={routes.projects[lang]}>{t.allProjects}<Arrow/></Link></div><Catalogue items={projects.slice(0,3)} lang={lang} kind="projects"/></div></section>
<section className="contact modern-contact" id="contact"><div className="container contact-layout"><div><p className="eyebrow">03 / {lang==="sq"?"Bashkëpunim":"Collaboration"}</p><h2>{t.contactTitle}</h2><p className="contact-copy">{t.contactText}</p></div><div className="contact-side"><a className="contact-email" href={`mailto:${email}`}>{email}<Arrow/></a>{localized(settings,"location",lang)&&<p>{localized(settings,"location",lang)}</p>}<div className="socials">{([["LinkedIn",settings?.linkedin],["GitHub",settings?.github],["ResearchGate",settings?.researchGate]] as const).map(([label,url])=>safeUrl(url)?<a key={label} href={safeUrl(url)} target="_blank" rel="noopener noreferrer">{label}<Arrow/></a>:null)}</div></div></div></section>
</main><SiteFooter lang={lang} settings={settings}/></>}
function Arrow(){return <svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" width="20" height="20"><path d="M5 12h14M13 6l6 6-6 6"/></svg>}
