import {SiteHeader,SiteFooter} from "./site-shell";
import {getSiteContent} from "@/lib/sanity";
import type {Language} from "@/lib/sanity";

const copy={
privacy:{
sq:{eyebrow:"Dokument zyrtar · Përditësuar së fundmi: Tetor 2026",title:"Politika e Privatësisë",intro:"Kjo politikë shpjegon si LindiMaps përpunon të dhënat personale kur vizitoni faqen publike, na kontaktoni ose përdorni shërbime dhe sisteme të autorizuara të LindiMaps.",sections:[
["1. Kush është përgjegjës për të dhënat","LindiMaps është përgjegjës për përpunimin e të dhënave personale të përshkruara në këtë politikë. Për pyetje mbi privatësinë mund të përdorni adresën zyrtare të kontaktit të publikuar në këtë faqe."],
["2. Të dhënat që mund të mblidhen","Faqja publike mund të përpunojë informacionin që jepni vullnetarisht përmes formularit të kontaktit, si emri, adresa e email-it, subjekti dhe përmbajtja e mesazhit. Infrastruktura teknike mund të përpunojë gjithashtu të dhëna standarde teknike, si adresa IP, lloji i shfletuesit, koha e kërkesës dhe të dhëna të nevojshme për sigurinë dhe funksionimin e shërbimit. Sistemet e autentikuara mund të përpunojnë të dhëna të llogarisë dhe përmbajtje të lidhur me funksionet e tyre."],
["3. Pse i përdorim të dhënat","Të dhënat përpunohen për t'iu përgjigjur kërkesave, për të ofruar dhe administruar shërbimet, për autentikim dhe funksionim teknik, për siguri dhe parandalim abuzimi, si dhe për të përmbushur detyrime ligjore ose kontraktuale kur zbatohen. Ne synojmë të përdorim vetëm të dhënat e nevojshme për secilin qëllim."],
["4. Formulari i kontaktit","Kur dërgoni formularin e kontaktit, informacioni i futur përdoret për të marrë dhe trajtuar kërkesën tuaj. Mos dërgoni të dhëna sensitive ose konfidenciale që nuk janë të nevojshme për kërkesën."],
["5. Ofruesit teknikë dhe shërbimet e palëve të treta","LindiMaps përdor ofrues teknikë për hostim, menaxhim përmbajtjeje, komunikim dhe, në sisteme të caktuara, autentikim ose ruajtje të të dhënave. Këta ofrues mund të përpunojnë të dhëna teknike ose personale vetëm në masën e nevojshme për ofrimin e shërbimeve përkatëse dhe sipas kushteve të tyre të zbatueshme."],
["6. Ruajtja e të dhënave","Të dhënat ruhen vetëm për aq kohë sa është e nevojshme për qëllimin për të cilin janë mbledhur, për vazhdimësinë e shërbimit, sigurinë, zgjidhjen e kërkesave ose përmbushjen e detyrimeve ligjore. Periudha konkrete mund të ndryshojë sipas llojit të të dhënave dhe shërbimit."],
["7. Siguria","Përdoren masa teknike dhe organizative të arsyeshme, përfshirë lidhje HTTPS dhe kontrolle aksesi aty ku aplikohen. Megjithatë, asnjë transmetim ose sistem online nuk mund të garantohet si absolutisht i sigurt."],
["8. Të drejtat tuaja","Në varësi të legjislacionit të zbatueshëm, mund të keni të drejtë të kërkoni informacion dhe akses në të dhënat tuaja, korrigjim, fshirje, kufizim ose kundërshtim ndaj përpunimit dhe, kur zbatohet, tërheqjen e pëlqimit. Kërkesat mund të dërgohen në adresën zyrtare të kontaktit."],
["9. Lidhjet dhe përmbajtja e jashtme","Faqja mund të përmbajë lidhje drejt platformave, publikimeve, hartave ose shërbimeve të palëve të treta. Kur largoheni nga LindiMaps, përpunimi i të dhënave rregullohet nga politikat e shërbimit përkatës."],
["10. Ndryshimet e kësaj politike","Politika mund të përditësohet kur ndryshojnë shërbimet, teknologjitë ose kërkesat ligjore. Data e përditësimit shfaqet në krye të dokumentit."]
]},
en:{eyebrow:"Official document · Last updated: October 2026",title:"Privacy Policy",intro:"This policy explains how LindiMaps processes personal data when you visit the public website, contact us, or use authorised LindiMaps services and systems.",sections:[
["1. Who is responsible for the data","LindiMaps is responsible for the processing of personal data described in this policy. Privacy questions may be sent to the official contact address published on this page."],
["2. Data we may collect","The public website may process information you voluntarily provide through the contact form, such as your name, email address, subject and message content. Technical infrastructure may also process standard technical information such as IP address, browser type, request time and data necessary for security and service operation. Authenticated systems may process account data and content associated with their functions."],
["3. Why we use data","Data is processed to respond to enquiries, provide and administer services, support authentication and technical operation, maintain security and prevent abuse, and meet applicable legal or contractual obligations. We aim to use only the data necessary for each purpose."],
["4. Contact form","When you submit the contact form, the information entered is used to receive and handle your enquiry. Please do not submit sensitive or confidential information that is not necessary for your request."],
["5. Technical providers and third-party services","LindiMaps uses technical providers for hosting, content management, communications and, in certain systems, authentication or data storage. These providers may process technical or personal data only to the extent necessary to provide the relevant services and subject to their applicable terms."],
["6. Data retention","Data is retained only for as long as necessary for the purpose for which it was collected, service continuity, security, resolution of enquiries or compliance with legal obligations. Specific retention periods may vary by data type and service."],
["7. Security","Reasonable technical and organisational measures are used, including HTTPS connections and access controls where applicable. However, no online transmission or system can be guaranteed to be absolutely secure."],
["8. Your rights","Depending on applicable law, you may have rights to request information and access to your personal data, correction, deletion, restriction or objection to processing and, where applicable, withdrawal of consent. Requests may be sent to the official contact address."],
["9. External links and content","The website may link to third-party platforms, publications, maps or services. Once you leave LindiMaps, data processing is governed by the policies of the relevant service."],
["10. Changes to this policy","This policy may be updated when services, technologies or legal requirements change. The update date is displayed at the top of this document."]
]}},
cookies:{
sq:{eyebrow:"Transparencë digjitale · Përditësuar së fundmi: Tetor 2026",title:"Politika e Cookies",intro:"Kjo politikë shpjegon përdorimin e cookies, ruajtjes lokale dhe teknologjive të ngjashme në faqen dhe shërbimet e LindiMaps.",sections:[
["1. Çfarë janë cookies dhe teknologjitë e ngjashme","Cookies dhe mekanizma si local storage mund të ruajnë sasi të vogla informacioni në pajisjen tuaj për funksionim, siguri, sesione ose preferenca."],
["2. Teknologjitë funksionale","LindiMaps mund të ruajë preferenca funksionale, si zgjedhja e paraqitjes light/dark, dhe të përdorë teknologji të nevojshme për funksionimin dhe sigurinë e faqes. Këto nuk përdoren nga LindiMaps për reklamim të personalizuar."],
["3. Sistemet e autentikuara","Sistemet e veçanta që kërkojnë hyrje mund të përdorin teknologji sesioni ose autentikimi për të mbajtur përdoruesin të identifikuar dhe për të mbrojtur aksesin. Bllokimi i tyre mund të pengojë funksionimin e sistemit."],
["4. Analitika dhe marketingu","LindiMaps nuk e paraqet përdorimin e cookies analitike ose marketingu si pjesë të domosdoshme të faqes publike. Nëse në të ardhmen aktivizohen teknologji jo të domosdoshme që kërkojnë pëlqim, kjo politikë dhe mekanizmi i pëlqimit do të përditësohen përpara aktivizimit të tyre."],
["5. Përmbajtja dhe shërbimet e jashtme","Lidhjet ose përmbajtja nga shërbime të jashtme mund t'ju çojnë në platforma që përdorin cookies sipas politikave të tyre. LindiMaps nuk kontrollon cookies të vendosura pasi përdoruesi kalon në një shërbim të jashtëm."],
["6. Si t'i kontrolloni","Mund të kufizoni ose fshini cookies dhe të dhënat e ruajtura përmes cilësimeve të shfletuesit. Çaktivizimi i teknologjive funksionale ose të autentikimit mund të ndikojë në preferenca ose në funksionimin e disa sistemeve."],
["7. Ndryshimet e politikës","Kjo politikë përditësohet kur ndryshojnë teknologjitë ose mënyra e përdorimit të tyre. Data e versionit aktual shfaqet në krye."]
]},
en:{eyebrow:"Digital transparency · Last updated: October 2026",title:"Cookie Policy",intro:"This policy explains the use of cookies, local storage and similar technologies across the LindiMaps website and services.",sections:[
["1. Cookies and similar technologies","Cookies and mechanisms such as local storage can store small amounts of information on your device for functionality, security, sessions or preferences."],
["2. Functional technologies","LindiMaps may store functional preferences, such as the light/dark appearance choice, and use technologies required for website operation and security. These are not used by LindiMaps for personalised advertising."],
["3. Authenticated systems","Separate systems requiring sign-in may use session or authentication technologies to keep users signed in and protect access. Blocking them may prevent the relevant system from functioning."],
["4. Analytics and marketing","LindiMaps does not present analytics or marketing cookies as a necessary part of the public website. If non-essential technologies requiring consent are enabled in the future, this policy and the consent mechanism will be updated before activation."],
["5. External content and services","Links or content from external services may lead you to platforms that use cookies under their own policies. LindiMaps does not control cookies placed after a user moves to an external service."],
["6. How to control them","You can restrict or delete cookies and stored data through your browser settings. Disabling functional or authentication technologies may affect preferences or the operation of some systems."],
["7. Policy changes","This policy is updated when technologies or their use change. The date of the current version is shown at the top."]
]}},
terms:{
sq:{eyebrow:"Marrëveshje ligjore · Përditësuar së fundmi: Tetor 2026",title:"Kushtet e Përdorimit",intro:"Këto kushte rregullojnë përdorimin e faqes publike, përmbajtjes dhe shërbimeve digjitale të LindiMaps.",sections:[
["1. Pranimi dhe përdorimi","Duke përdorur LindiMaps, ju pranoni t'i përdorni faqen, materialet dhe shërbimet vetëm për qëllime të ligjshme dhe në përputhje me legjislacionin e zbatueshëm. Disa sisteme ose funksione mund të kenë akses të kufizuar dhe të kërkojnë autentikim."],
["2. Pronësia intelektuale","Marka, logoja, dizajni, kodi origjinal, tekstet, grafikat, hartat dhe materialet e krijuara nga LindiMaps mbrohen nga të drejtat përkatëse, përveç rasteve kur shënohet ndryshe. Materialet, të dhënat, publikimet ose logot e palëve të treta mbeten pronë e mbajtësve përkatës të të drejtave."],
["3. Projekte, kërkim dhe publikime","Paraqitja e një projekti, publikimi ose bashkëpunimi në LindiMaps nuk nënkupton automatikisht pronësi ekskluzive ose autorësi nga LindiMaps. Kreditë, institucionet, autorët dhe burimet e shënuara në materialin përkatës duhet të respektohen."],
["4. Harta dhe të dhëna gjeohapësinore","Hartat, analizat GIS, modelet, imazhet, koordinatat dhe të dhënat gjeohapësinore mund të kenë kufizime në saktësi, rezolucion, shkallë, burim ose aktualitet. Për vendime profesionale, ligjore, kadastrale, inxhinierike ose të sigurisë, informacioni duhet të verifikohet me burimin autoritativ dhe profesionistin përkatës."],
["5. Përdorimi i ndaluar","Nuk lejohet ndërhyrja e paautorizuar në sisteme, anashkalimi i kontrolleve të aksesit, shpërndarja e kodeve dëmtuese, abuzimi me formularët ose llogaritë, apo mbledhja automatike e të dhënave në kundërshtim me ligjin, të drejtat e palëve të treta ose kufizimet e shërbimit."],
["6. Shërbimet dhe lidhjet e palëve të treta","LindiMaps mund të lidhet me platforma, harta, publikime, rrjete sociale ose shërbime të palëve të treta. Disponueshmëria, përmbajtja dhe kushtet e këtyre shërbimeve kontrollohen nga ofruesit përkatës."],
["7. Disponueshmëria dhe ndryshimet","Synojmë funksionim të qëndrueshëm, por nuk garantojmë që çdo funksion do të jetë pa ndërprerje ose gabime. Përmbajtja, shërbimet dhe funksionet mund të përditësohen, zëvendësohen ose ndërpriten kur është e nevojshme."],
["8. Kufizimi i përgjegjësisë","Në masën e lejuar nga ligji, LindiMaps nuk mban përgjegjësi për vendime të marra vetëm mbi bazën e materialeve informative të faqes, për pasaktësi që burojnë nga burime të jashtme ose për ndërprerje jashtë kontrollit të arsyeshëm të LindiMaps."],
["9. Privatësia","Përpunimi i të dhënave personale dhe përdorimi i teknologjive të ruajtjes shpjegohen në Politikën e Privatësisë dhe Politikën e Cookies të LindiMaps."],
["10. Ndryshimet e kushteve","Këto kushte mund të përditësohen për të pasqyruar ndryshime në shërbime, teknologji ose kërkesa ligjore. Versioni dhe data e publikuar në këtë faqe përbëjnë versionin aktual."]
]},
en:{eyebrow:"Legal agreement · Last updated: October 2026",title:"Terms of Use",intro:"These terms govern use of the LindiMaps public website, content and digital services.",sections:[
["1. Acceptance and use","By using LindiMaps, you agree to use the website, materials and services only for lawful purposes and in accordance with applicable law. Certain systems or functions may have restricted access and require authentication."],
["2. Intellectual property","The LindiMaps brand, logo, design, original code, text, graphics, maps and materials are protected by applicable rights unless otherwise stated. Third-party materials, data, publications and logos remain the property of their respective rights holders."],
["3. Projects, research and publications","Display of a project, publication or collaboration on LindiMaps does not automatically imply exclusive ownership or authorship by LindiMaps. Credits, institutions, authors and sources identified with the relevant material must be respected."],
["4. Maps and geospatial data","Maps, GIS analyses, models, imagery, coordinates and geospatial data may have limitations in accuracy, resolution, scale, source or currency. For professional, legal, cadastral, engineering or safety decisions, information should be verified against the authoritative source and an appropriate professional."],
["5. Prohibited use","Unauthorised interference with systems, circumvention of access controls, distribution of malicious code, abuse of forms or accounts, or automated collection of data contrary to law, third-party rights or service restrictions is prohibited."],
["6. Third-party services and links","LindiMaps may link to third-party platforms, maps, publications, social networks or services. Availability, content and terms of those services are controlled by their respective providers."],
["7. Availability and changes","We aim to provide reliable operation but do not guarantee that every function will be uninterrupted or error-free. Content, services and functions may be updated, replaced or discontinued when necessary."],
["8. Limitation of liability","To the extent permitted by law, LindiMaps is not responsible for decisions made solely on the basis of informational website materials, inaccuracies originating from external sources, or interruptions outside LindiMaps' reasonable control."],
["9. Privacy","Processing of personal data and use of storage technologies are described in the LindiMaps Privacy Policy and Cookie Policy."],
["10. Changes to these terms","These terms may be updated to reflect changes in services, technology or legal requirements. The version and date published on this page constitute the current version."]
]}}
} as const;

export default async function LegalPage({lang,type}:{lang:Language;type:"privacy"|"terms"|"cookies"}){
 const c=copy[type][lang];
 const data=await getSiteContent();
 const languageRoutes={sq:type==="privacy"?"/sq/privacy":type==="terms"?"/sq/termsofuse":"/sq/cookies",en:type==="privacy"?"/en/privacy":type==="terms"?"/en/termsofuse":"/en/cookies"};
 return <><SiteHeader lang={lang} page="home" settings={data.settings} languageRoutes={languageRoutes}/><main id="main" className="legal-page" tabIndex={-1}><section className="legal-hero"><p>{c.eyebrow}</p><h1>{c.title}</h1><span>{c.intro}</span></section><article className="legal-content">{c.sections.map(([title,text])=><section key={title}><h2>{title}</h2><p>{text}</p></section>)}<aside><h3>{lang==="sq"?"Pyetje ose kërkesa?":"Questions or requests?"}</h3><p>{lang==="sq"?"Për çështje që lidhen me këtë dokument ose me të dhënat tuaja, na kontaktoni në adresën zyrtare të LindiMaps.":"For matters related to this document or your personal data, contact us at the official LindiMaps address."}</p><a href={`mailto:${data.settings?.email||"contact.lindimaps@gmail.com"}`}>{data.settings?.email||"contact.lindimaps@gmail.com"} ↗</a></aside></article></main><SiteFooter lang={lang} settings={data.settings}/></>
}