import {notFound} from "next/navigation";
import {getSiteContent,type Language} from "@/lib/sanity";
import {getServiceDetail} from "@/data/service-details";
import {SiteHeader,SiteFooter} from "./site-shell";
const techIcons:Record<string,string>={"ArcGIS Pro":"arcgis","ArcGIS Online / Enterprise":"arcgis","QGIS":"qgis","PostGIS":"postgresql","Python":"python","GeoPackage":"sqlite","Agisoft Metashape":"agisoft","Pix4D":"pix4d","Next.js":"nextdotjs","React":"react","TypeScript":"typescript","Sanity CMS":"sanity","Vercel":"vercel","Cloudflare":"cloudflare","REST APIs":"fastapi"};
export default async function ServiceDetailPage({lang,slug}:{lang:Language;slug:string}){
 const d=getServiceDetail(slug);if(!d)notFound();const data=await getSiteContent();const sq=lang==="sq";
 const cms=data.services.find(item=>item.slug===slug||item.titleSq?.trim().toLowerCase()===d.titleSq.toLowerCase()||item.titleEn?.trim().toLowerCase()===d.titleEn.toLowerCase());
 const title=sq?(cms?.titleSq||d.titleSq):(cms?.titleEn||d.titleEn);
 const lead=sq?(cms?.leadSq||d.leadSq):(cms?.leadEn||d.leadEn), intro=sq?(cms?.introSq||d.introSq):(cms?.introEn||d.introEn);
 const capabilities=sq?(cms?.capabilitiesSq?.length?cms.capabilitiesSq:d.capabilitiesSq):(cms?.capabilitiesEn?.length?cms.capabilitiesEn:d.capabilitiesEn);
 const workflow=sq?(cms?.workflowSq?.length?cms.workflowSq:d.workflowSq):(cms?.workflowEn?.length?cms.workflowEn:d.workflowEn);
 const deliverables=sq?(cms?.deliverablesSq?.length?cms.deliverablesSq:d.deliverablesSq):(cms?.deliverablesEn?.length?cms.deliverablesEn:d.deliverablesEn);
 const applications=sq?(cms?.applicationsSq?.length?cms.applicationsSq:d.applicationsSq):(cms?.applicationsEn?.length?cms.applicationsEn:d.applicationsEn);
 const technologies:{name:string;logo?:string;url?:string}[]=cms?.serviceTechnologies?.length?cms.serviceTechnologies:d.technologies.map(name=>({name}));
 const ctaTitle=sq?(cms?.ctaTitleSq||"Ke një projekt që kërkon këtë ekspertizë?"):(cms?.ctaTitleEn||"Have a project that needs this expertise?");
 const ctaText=sq?(cms?.ctaTextSq||"Përshkruaj objektivin, të dhënat që ke dhe rezultatin që kërkon."):(cms?.ctaTextEn||"Describe your objective, the data you have and the result you need.");
 const languageRoutes={sq:`/sq/sherbime/${slug}/`,en:`/en/services/${slug}/`};
 const base="https://www.lindimaps.com";const servicePath=languageRoutes[lang];const servicesPath=sq?"/sq/sherbime/":"/en/services/";
 const structuredData={"@context":"https://schema.org","@graph":[{"@type":"Service","@id":base+servicePath+"#service",name:title,description:lead,url:base+servicePath,provider:{"@type":"Organization","@id":base+"/#organization",name:"LindiMaps",url:base}},{"@type":"BreadcrumbList","@id":base+servicePath+"#breadcrumb",itemListElement:[{"@type":"ListItem",position:1,name:sq?"Kreu":"Home",item:base+(sq?"/":"/en")},{"@type":"ListItem",position:2,name:sq?"Shërbime":"Services",item:base+servicesPath},{"@type":"ListItem",position:3,name:title,item:base+servicePath}]}]};
 return <><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(structuredData).replace(/</g,"\\u003c")}}/><SiteHeader lang={lang} page="services" settings={data.settings} languageRoutes={languageRoutes}/><main id="main" className="service-detail-page">
 <section className="service-detail-hero"><div className="container"><p className="eyebrow">LINDIMAPS / {sq?"SHERBIME":"SERVICES"}</p><h1>{title}</h1><p className="service-detail-lead">{lead}</p><a className="service-detail-back" href={sq?"/sq/sherbime/":"/en/services/"}>{sq?"Të gjitha shërbimet":"All services"}</a></div></section>
 <section className="container service-detail-content"><div className="service-detail-intro"><span>01</span><div><p className="eyebrow">{sq?"QASJA":"APPROACH"}</p><h2>{sq?"Nga nevoja te një rezultat i përdorshëm.":"From the requirement to a usable result."}</h2><p>{intro}</p></div></div>
 <div className="service-detail-columns"><section><p className="eyebrow">02 / {sq?"KAPACITETET":"CAPABILITIES"}</p><h2>{sq?"Çfarë përfshin":"What it covers"}</h2><ul>{capabilities.map(x=><li key={x}>{x}</li>)}</ul></section><section><p className="eyebrow">03 / WORKFLOW</p><h2>{sq?"Si realizohet":"How it works"}</h2><ol>{workflow.map((x,i)=><li key={x}><span>{String(i+1).padStart(2,"0")}</span>{x}</li>)}</ol></section></div>
 <div className="service-detail-columns service-detail-secondary"><section><p className="eyebrow">04 / {sq?"DORËZIMET":"DELIVERABLES"}</p><h2>{sq?"Çfarë merr klienti":"What the client receives"}</h2><ul>{deliverables.map(x=><li key={x}>{x}</li>)}</ul></section><section><p className="eyebrow">05 / {sq?"PËRDORIME":"APPLICATIONS"}</p><h2>{sq?"Ku aplikohet":"Where it applies"}</h2><ul>{applications.map(x=><li key={x}>{x}</li>)}</ul></section></div>
 <section className="service-detail-tech"><p className="eyebrow">06 / TECHNOLOGY</p><h2>{sq?"Teknologji dhe standarde":"Technology and standards"}</h2><div className="service-tech-grid">{[...technologies,...technologies].map((tech,index)=>{const icon=techIcons[tech.name];const logo=tech.logo|| (icon?`https://cdn.simpleicons.org/${icon}`:"");const item=<>{logo?<img src={logo} alt="" aria-hidden="true"/>:<i aria-hidden="true">{tech.name.slice(0,2).toUpperCase()}</i>}<b>{tech.name}</b></>;return tech.url?<a className="service-tech-item" href={tech.url} target="_blank" rel="noopener noreferrer" key={`${tech.name}-${index}`} aria-hidden={index>=technologies.length}>{item}</a>:<span className="service-tech-item" key={`${tech.name}-${index}`} aria-hidden={index>=technologies.length}>{item}</span>})}</div></section>
 <section className="service-detail-cta"><div><p className="eyebrow">LINDIMAPS / START A PROJECT</p><h2>{ctaTitle}</h2><p>{ctaText}</p></div><a className="service-project-button" href={sq?"/sq/kontakte/":"/en/contact/"}>{sq?"Diskuto projektin":"Discuss the project"} <span aria-hidden="true">→</span></a></section></section></main><SiteFooter lang={lang} settings={data.settings}/></>
}