import {defineField, defineType} from 'sanity'

export const projectType = defineType({
  name: 'project',
  title: 'Projektet',
  type: 'document',
  fields: [
    defineField({
      name: 'imageUrl',
      title: 'Imazhi origjinal – URL',
      description: 'Përdoret derisa të ngarkoni një imazh të ri.',
      type: 'url',
    }),
    defineField({
      name: 'titleSq',
      title: 'Titulli',
      type: 'string',
      validation: (r) => r.required(),
    }),
    defineField({name: 'titleEn', title: 'Title (EN)', type: 'string'}),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {source: 'titleSq', maxLength: 96},
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'categories',
      title: 'Kategoritë',
      description: 'Një projekt mund të përfshihet në një ose më shumë kategori.',
      type: 'array',
      of: [{type: 'reference', to: [{type: 'projectCategory'}]}],
      validation: (r) => r.unique(),
    }),
    defineField({name: 'summarySq', title: 'Përmbledhje', type: 'text', rows: 3}),
    defineField({name: 'summaryEn', title: 'Summary (EN)', type: 'text', rows: 3}),
    defineField({name: 'descriptionSq', title: 'Përshkrimi', type: 'array', of: [{type: 'block'}]}),
    defineField({
      name: 'descriptionEn',
      title: 'Description (EN)',
      type: 'array',
      of: [{type: 'block'}],
    }),
    defineField({
      name: 'coverImage',
      title: 'Imazhi kryesor',
      type: 'image',
      options: {hotspot: true},
      fields: [
        {name: 'altSq', title: 'Alt text', type: 'string'},
        {name: 'altEn', title: 'Alt text (EN)', type: 'string'},
      ],
    }),
    defineField({
      name: 'gallery',
      title: 'Galeria',
      type: 'array',
      of: [{type: 'image', options: {hotspot: true}}],
    }),
    defineField({
      name: 'technologies',
      title: 'Teknologjitë',
      type: 'array',
      of: [{type: 'string'}],
      options: {layout: 'tags'},
    }),
    defineField({name: 'roleSq', title: 'Roli', type: 'string'}),
    defineField({name: 'roleEn', title: 'Role (EN)', type: 'string'}),
    defineField({name: 'client', title: 'Institucioni / Klienti', type: 'string'}),
    defineField({name: 'clientEn', title: 'Institution / Client (EN)', type: 'string'}),
    defineField({name: 'year', title: 'Viti', type: 'number', validation: (r) => r.integer().min(1900).max(2100)}),
    defineField({name: 'liveUrl', title: 'WebGIS / Live URL', type: 'url'}),
    defineField({name: 'githubUrl', title: 'GitHub URL', type: 'url'}),
    defineField({name: 'location', title: 'Vendndodhja', type: 'geopoint'}),
    defineField({
      name: 'featured',
      title: 'Shfaq si projekt i veçuar',
      type: 'boolean',
      initialValue: false,
    }),
    defineField({name: 'order', title: 'Renditja', type: 'number', validation: (r) => r.integer().min(0)}),
  ],
  preview: {select: {title: 'titleSq', subtitle: 'category', media: 'coverImage'}},
})
