import {defineField, defineType} from 'sanity'
export const siteSettingsType = defineType({
  name: 'siteSettings',
  title: 'Konfigurimi i faqes',
  type: 'document',
  fields: [
    defineField({
      name: 'useStarterContent',
      title: 'Përdor përmbajtjen fillestare kur mungon në CMS',
      type: 'boolean',
      initialValue: false,
    }),
    defineField({
      name: 'siteName',
      title: 'Emri i faqes',
      type: 'string',
      initialValue: 'LindiMaps',
      validation: (r) => r.required().min(2).max(80),
    }),
    defineField({name: 'logo', title: 'Logo', type: 'image'}),
    defineField({name: 'logoDark', title: 'Logo për dark mode', type: 'image'}),
    defineField({name: 'email', title: 'Email', type: 'string', validation: (r) => r.email()}),
    defineField({name: 'locationSq', title: 'Vendndodhja', type: 'string'}),
    defineField({name: 'locationEn', title: 'Location (EN)', type: 'string'}),
    defineField({name: 'linkedin', title: 'LinkedIn', type: 'url'}),
    defineField({name: 'instagram', title: 'Instagram', type: 'url'}),
    defineField({name: 'github', title: 'GitHub', type: 'url'}),
    defineField({name: 'researchGate', title: 'ResearchGate', type: 'url'}),
    defineField({name: 'seoTitle', title: 'SEO title', type: 'string', validation: (r) => r.max(70)}),
    defineField({name: 'seoDescriptionSq', title: 'SEO description', type: 'text', rows: 3, validation: (r) => r.max(180)}),
    defineField({name: 'seoDescriptionEn', title: 'SEO description (EN)', type: 'text', rows: 3, validation: (r) => r.max(180)}),
    defineField({name: 'ogImage', title: 'Social / Open Graph image', type: 'image'}),
  ],
  preview: {prepare: () => ({title: 'LindiMaps – Site settings'})},
})
