import {defineField, defineType} from 'sanity'
export const siteSettingsType = defineType({
  name: 'siteSettings',
  title: 'Konfigurimi i faqes',
  type: 'document',
  groups: [
    {name:'general',title:'Faqja',default:true},
    {name:'navigation',title:'Header & Menu'},
    {name:'footer',title:'Footer'},
    {name:'social',title:'Rrjetet sociale'},
    {name:'seo',title:'SEO'},
  ],
  fields: [
    defineField({group:'general',name:'useStarterContent',title:'Përdor përmbajtjen fillestare kur mungon në CMS',type:'boolean',initialValue:false}),
    defineField({group:'general',name:'siteName',title:'Emri i faqes',type:'string',initialValue:'LindiMaps',validation:(r)=>r.required().min(2).max(80)}),
    defineField({group:'general',name:'logo',title:'Logo – Header / Light',description:'Logoja kryesore e faqes. Nëse lihet bosh përdoret logoja aktuale.',type:'image'}),
    defineField({group:'general',name:'logoDark',title:'Logo – Dark mode',description:'Opsionale. Nëse lihet bosh përdoret logoja kryesore.',type:'image'}),
    defineField({group:'general',name:'logoFooter',title:'Logo – Footer',description:'Opsionale. Nëse lihet bosh përdoret logoja kryesore.',type:'image'}),
    defineField({group:'general',name:'favicon',title:'Site Icon / Favicon',description:'Ikona që shfaqet në tab-in e browser-it. Preferohet imazh katror.',type:'image'}),
    defineField({
      group:'navigation',
      name:'headerMenu',
      title:'Header & Menu',
      description:'Opsionale. Nëse lihet bosh, përdoret menuja aktuale e faqes. Rendit elementet me drag & drop. Mbështet një nivel submenuje.',
      type:'array',
      of:[{type:'object',fields:[
        defineField({name:'labelSq',title:'Emri (SQ)',type:'string',validation:(r)=>r.required().max(50)}),
        defineField({name:'labelEn',title:'Name (EN)',type:'string',validation:(r)=>r.required().max(50)}),
        defineField({name:'urlSq',title:'Linku (SQ)',description:'P.sh. /sq/sherbime ose https://...',type:'string',validation:(r)=>r.required()}),
        defineField({name:'urlEn',title:'Link (EN)',description:'P.sh. /en/services ose https://...',type:'string',validation:(r)=>r.required()}),
        defineField({name:'visible',title:'Shfaq në menu',type:'boolean',initialValue:true}),
        defineField({name:'newTab',title:'Hap në tab të ri',type:'boolean',initialValue:false}),
        defineField({
          name:'children',title:'Submenu',description:'Opsionale. Vetëm një nivel submenuje.',
          type:'array',of:[{type:'object',fields:[
            defineField({name:'labelSq',title:'Emri (SQ)',type:'string',validation:(r)=>r.required().max(50)}),
            defineField({name:'labelEn',title:'Name (EN)',type:'string',validation:(r)=>r.required().max(50)}),
            defineField({name:'urlSq',title:'Linku (SQ)',type:'string',validation:(r)=>r.required()}),
            defineField({name:'urlEn',title:'Link (EN)',type:'string',validation:(r)=>r.required()}),
            defineField({name:'visible',title:'Shfaq',type:'boolean',initialValue:true}),
            defineField({name:'newTab',title:'Hap në tab të ri',type:'boolean',initialValue:false}),
          ],preview:{select:{title:'labelSq',subtitle:'labelEn'}}}]
        }),
      ],preview:{select:{title:'labelSq',subtitle:'labelEn'}}}]
    }),
    defineField({group:'footer',name:'footerKicker',title:'Footer – Kicker',type:'string'}),
    defineField({group:'footer',name:'footerHeadline',title:'Footer – Titulli',type:'string'}),
    defineField({group:'footer',name:'footerDescriptionSq',title:'Footer – Përshkrimi (SQ)',type:'text',rows:3}),
    defineField({group:'footer',name:'footerDescriptionEn',title:'Footer – Description (EN)',type:'text',rows:3}),
    defineField({group:'footer',name:'footerCtaSq',title:'Footer – CTA (SQ)',type:'string'}),
    defineField({group:'footer',name:'footerCtaEn',title:'Footer – CTA (EN)',type:'string'}),
    defineField({group:'footer',name:'footerCtaUrlSq',title:'Footer – CTA link (SQ)',type:'string'}),
    defineField({group:'footer',name:'footerCtaUrlEn',title:'Footer – CTA link (EN)',type:'string'}),
    defineField({group:'footer',name:'footerHoursSq',title:'Footer – Orari (SQ)',type:'string'}),
    defineField({group:'footer',name:'footerHoursEn',title:'Footer – Hours (EN)',type:'string'}),
    defineField({group:'footer',name:'footerCapabilitiesSq',title:'Footer – Aftësi (SQ)',type:'array',of:[{type:'string'}]}),
    defineField({group:'footer',name:'footerCapabilitiesEn',title:'Footer – Capabilities (EN)',type:'array',of:[{type:'string'}]}),
    defineField({group:'general',name:'presentationVideo',title:'Video prezantuese – Aktivitetet & Galeria',description:'Video fallback që shfaqet te Aktivitetet ose Galeria vetëm kur nuk ka përmbajtje të publikuar. MP4/WebM.',type:'file',options:{accept:'video/mp4,video/webm'}}),
    defineField({group:'general',name:'presentationVideoPoster',title:'Poster i videos prezantuese',description:'Opsionale. Imazhi që shfaqet para nisjes së videos.',type:'image',options:{hotspot:true}}),
    defineField({group:'general',name:'email',title:'Email',type:'string',validation:(r)=>r.email()}),
    defineField({group:'general',name:'locationSq',title:'Vendndodhja',type:'string'}),
    defineField({group:'general',name:'locationEn',title:'Location (EN)',type:'string'}),
    defineField({group:'social',name:'linkedin',title:'LinkedIn',type:'url'}),
    defineField({group:'social',name:'linkedinIcon',title:'LinkedIn – Ikona',description:'Opsionale. Nëse lihet bosh përdoret ikona automatike e LinkedIn.',type:'image'}),
    defineField({group:'social',name:'instagram',title:'Instagram',type:'url'}),
    defineField({group:'social',name:'instagramIcon',title:'Instagram – Ikona',description:'Opsionale. Nëse lihet bosh përdoret ikona automatike e Instagram.',type:'image'}),
    defineField({group:'social',name:'github',title:'GitHub',type:'url'}),
    defineField({group:'social',name:'githubIcon',title:'GitHub – Ikona',description:'Opsionale. Nëse lihet bosh përdoret ikona automatike e GitHub.',type:'image'}),
    defineField({group:'social',name:'researchGate',title:'ResearchGate',type:'url'}),
    defineField({group:'social',name:'researchGateIcon',title:'ResearchGate – Ikona',description:'Opsionale. Nëse lihet bosh përdoret ikona automatike e ResearchGate.',type:'image'}),
    defineField({
      group:'social',
      name:'footerSocialLinks',
      title:'Footer – Rrjetet sociale shtesë',
      description:'Shto rrjete të tjera sociale në footer. Për rrjetet e njohura ikona gjenerohet automatikisht; ikona e ngarkuar ka përparësi.',
      type:'array',
      of:[{type:'object',fields:[
        defineField({name:'name',title:'Emri i rrjetit',type:'string',validation:(r)=>r.required().min(2).max(40)}),
        defineField({name:'url',title:'Linku',type:'url',validation:(r)=>r.required()}),
        defineField({name:'icon',title:'Ikona',description:'Opsionale. Ngarko ikonën tënde; nëse lihet bosh përdoret ikona automatike kur rrjeti njihet.',type:'image'})
      ],preview:{select:{title:'name',subtitle:'url',media:'icon'}}}],
    }),
    defineField({group:'seo',name:'seoTitle',title:'SEO title',type:'string',validation:(r)=>r.max(70)}),
    defineField({group:'seo',name:'seoDescriptionSq',title:'SEO description',type:'text',rows:3,validation:(r)=>r.max(180)}),
    defineField({group:'seo',name:'seoDescriptionEn',title:'SEO description (EN)',type:'text',rows:3,validation:(r)=>r.max(180)}),
    defineField({group:'seo',name:'ogImage',title:'Social / Open Graph image',type:'image'}),
  ],
  preview:{prepare:()=>({title:'LindiMaps – Site settings'})},
})